apiVersion: v1
kind: Service
metadata:
  name: lmaas-service
  namespace: lmaas
spec:
  selector:
    app: lmaas-service
  type: LoadBalancer # Change to LoadBalancer  NodePort if desired
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
